site_name: Informatik 2 Notizen
site_url: https://github.com/doodlezucc/studium-notizen
site_dir: public
docs_dir: wiki

theme:
  name: material
  language: de
  palette:
    primary: green
    accent: light green
    scheme: slate
  features:
    - navigation.sections
    - navigation.footer

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - roamlinks
  - awesome-pages
