site_name: Informatik 2 Notizen
site_url: https://github.com/doodlezucc/studium-notizen
site_dir: public
docs_dir: wiki

theme:
  name: material
  palette:
    primary: brown
    accent: amber
    scheme: slate

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition

plugins:
  - search
  - roamlinks
